src/documents/APIChangesFrom1_5To2_0.md
src/documents/AuxiliarySchemaForPreferencesFramework.md
src/documents/ComponentConfigurationOptions.md
src/documents/ConnectingThePartsOfAPreferencesEditor.md
src/documents/Enactors.md
src/documents/IoCReferences.md
src/documents/LocalizationInThePreferencesFramework.md
src/documents/Panels.md
src/documents/README.md
src/documents/TextToSpeechAPI.md
src/documents/tutorial-creatingAPreferencesEditorUsingThePreferencesFramework/CreatingAnAuxiliarySchema.md
src/documents/tutorial-creatingAPreferencesEditorUsingThePreferencesFramework/CreatingEnactors.md
src/documents/tutorial-gettingStartedWithInfusion/EventedComponents.md
src/documents/tutorial-gettingStartedWithInfusion/Subcomponents.md
src/documents/tutorial-migratingToInfusion2.0/UIOptionsMigration.md

http://issues.fluidproject.org/browse/FLUID-5603

FLUID-5603: Add the API doc for the text to speech component

---

src/documents/tutorial-usingStringTemplates/UsingStringTemplates.md

I tried to follow the conventions from other docs in terms of format and links.  Please review and comment.

GPII-1120: Added draft tutorial for fluid.stringTemplate().

---

docpad.js
site-structure.json
src/documents/ImageReordererAPI.md
src/documents/to-do/ImageReordererAPI.md
src/documents/to-do/TalkingToTheServerUsingTheAfterMoveEvent.md
src/static/css/infusion-docs.css

- Some minor styling tweaks
- Update site ToC to point to new doc

FLUID-5641: Added ImageReordererAPI doc

---

src/documents/ComponentConfigurationOptions.md
src/static/css/infusion-docs.css

- Added underline for code blocks which are also links.
- Changed border styling of code blocks
- removed padding and margins on code blocks to fix overlapping issue
- minor fix on Component Configuration Options document
Test using the following docs:
ComponentGrades.html
ComponentConfigurationOptions.html

FLUID-5640: Updated code block styling

---

README.md

Added a note that about using the gh-pages plugin to push changes to the production site.

NOJIRA: updated README

---

src/documents/EventInjectionAndBoiling.md

See [GPII-1236](https://issues.gpii.net/browse/GPII-1236).
I just realized I should probably be submitting these against the FLUID JIRA instance.  If it's OK, I'll do that from now on?

Fixed typo in example.

---

src/documents/PreferencesEditor.md

This matches the Infusion pull https://github.com/fluid-project/infusion/pull/660/files

FLUID-5831: Corrected docs for prefs editor storeType

---

README.md
src/documents/index.md

for anyone who (like me) keeps landing on the github documentation page and want access to the other infusion related resources

FLUID-5849: Added link to documentation and homepage to README

---

src/documents/DOMBinder.md
src/documents/DOMBinderAPI.md

FLUID-5821: Added description of newly specified behaviour for DOM binder mismatches

---

src/documents/ComponentGrades.md
src/documents/IoCAPI.md
src/documents/jqUnit.md

Found a few links that were wrong or incomplete.

NOJIRA: Fixed a few links

---

src/documents/FrameworkConcepts.md

Corrected the link syntax the "EventEmitter" link.

NOJIRA: Fixed link syntax

---

src/documents/Builder.md

This adds some documentation of switching between native and jQuery adjuster widgets for the now-merged PR: https://github.com/fluid-project/infusion/pull/724

FLUID-5892: add documentation of context-awareness behaviour for prefs adjuster widgets

---

src/documents/AuxiliarySchemaForPreferencesFramework.md
src/documents/Builder.md
src/documents/LocalizationInThePreferencesFramework.md
src/documents/UserInterfaceOptionsAPI.md
src/documents/tutorial-userInterfaceOptions/UserInterfaceOptions.md
src/layouts/default.html.handlebars

https://issues.fluidproject.org/browse/FLUID-5934

FLUID-5934: Correcting paths for prefs framework prefixes

---

src/documents/APIChangesFrom1_5To2_0.md
src/documents/tutorial-prefsFramework/CreatingANewAdjusterUI.md

https://issues.fluidproject.org/browse/FLUID-5194
Infusion PR: https://github.com/fluid-project/infusion/pull/739

FLUID-5194: Updating docs based on changes to Infusion

---

src/documents/TextToSpeechAPI.md

Updates the TTS docs in light of the changes coming from the FLUID-5936 PR: https://github.com/fluid-project/infusion/pull/732

FLUID-5950: remove events removed due to FLUID-5936; add documentation of model paths.

---

src/documents/IoCAPI.md

Code pull request: https://github.com/fluid-project/infusion/pull/747

GPII-1680: Document fluid.componentForPath(path)

---

src/documents/FunctionGrades.md
src/documents/ModelRelay.md
src/documents/tutorial-gettingStartedWithInfusion/RendererComponents.md

https://issues.fluidproject.org/browse/FLUID-6078

FLUID-6078: Updating links to Model Transformation API

---

src/documents/PromisesAPI.md

https://issues.fluidproject.org/browse/FLUID-6084

FLUID-6084: Update the promise API doc to reflect the change on fluid.promise.map() via FLUID-5986

---

src/documents/NodeAPI.md

@simonbates - would you be able to take a quick look - thanks!

FLUID-6088: Updates and improvements to Node API docs

---

src/documents/HowToUseTheRenderer.md
src/documents/RendererComponents.md
src/documents/UploaderAPI.md
src/documents/tutorial-migratingToInfusion1.5/UIOptionsMigration.md

https://issues.fluidproject.org/browse/FLUID-6096

FLUID-6096: Removing old "new" declarations.

---

src/documents/tutorial-userInterfaceOptions/UserInterfaceOptions.md

@jobara 
Taking what alychow had started, I've updated the examples, and clarified some of the text. Please take a look.

FLUID-5977

---

site-structure.json
src/documents/DeprecatedIn2_0.md

https://issues.fluidproject.org/browse/FLUID-6121
Please merge both into master and the 2.x.x branch.

FLUID-6121: Documenting Infusion 2.0 deprecations.

---

src/documents/CoreAPI.md
src/documents/ModelTransformationAPI.md

Also add documentation for fluid.roundToDecimal
https://issues.fluidproject.org/browse/FLUID-6125
Related to https://github.com/fluid-project/infusion/pull/807

FLUID-6125: Updates documentation numberToString transform

---

site-structure.json
src/documents/APIChangesFrom2_0To3_0.md
src/documents/SwitchAPI.md

https://issues.fluidproject.org/browse/FLUID-5708
Related Infusion PR: https://github.com/fluid-project/infusion/pull/811

FLUID-5708: Documentation related to switch component and adjuster

---

src/documents/APIChangesFrom2_0To3_0.md
src/documents/ModelTransformationAPI.md

https://issues.fluidproject.org/browse/FLUID-6172
Infusion PR: https://github.com/fluid-project/infusion/pull/837

FLUID-6172: Documenting using fluid.transforms.round to round to decimal

---

src/documents/APIChangesFrom2_0To3_0.md
src/documents/ModelTransformationAPI.md

https://issues.fluidproject.org/browse/FLUID-6174
Infusion PR: https://github.com/fluid-project/infusion/pull/838

FLUID-6174: Updated docs for changes to add input option to valueMapper

---

src/ghpages-files/googleb25567dcba3da270.html

Need to add this file to verify ownership so that we can track it with Google Search Console.

NOJIRA: Adding verification for Google Search Console

---

src/documents/APIChangesFrom2_0To3_0.md

https://issues.fluidproject.org/browse/FLUID-5534
Infusion PR: https://github.com/fluid-project/infusion/pull/844

FLUID-5534: Added API change information

---

src/documents/APIChangesFrom2_0To3_0.md
src/documents/ImageReordererAPI.md

Modified docs to account for https://issues.fluidproject.org/browse/FLUID-4016

Modified docs to account for changes made in FLUID-4016

---

src/documents/tutorial-userInterfaceOptions/UserInterfaceOptions.md

https://issues.fluidproject.org/browse/FLUID-6232
Updated the UI Options documentation to include the npm install method of acquiring Infusion

FLUID-6232: Update the UI Options documentation to include the npm install method of acquiring Infusion

---

Gruntfile.js
docpad.js
src/documents/APIChangesFrom2_0To3_0.md
src/documents/Enactors.md
src/documents/NodeAPI.md
src/documents/SwitchAPI.md
src/documents/tutorial-gettingStartedWithInfusion/SetUpYourEnvironment.md
src/documents/tutorial-prefsFramework/CreatingAPrefsEditor.md
src/documents/tutorial-prefsFrameworkMinimalFootprint/MinimalFootprint.md
src/documents/tutorial-userInterfaceOptions/UserInterfaceOptions.md
src/static/js/search.js

https://issues.fluidproject.org/browse/FLUID-6562

FLUID-6562: Update for rename of default branch to main

---

src/static/css/infusion-docs.css

Fixes the contrast issues related to link colour (normal and hover states).

fix: resolve colour contrast issues (fix #192)

---

src/_data/siteStructure.json
src/documents/tutorial-userInterfaceOptions/IntegratingUIOptionsStylingPreferences.md
src/documents/tutorial-userInterfaceOptions/WorkingWithUserInterfaceOptions.md

Adds documentation/tutorial for UIO/Prefs Framework CSS custom properties.
https://issues.fluidproject.org/browse/FLUID-6691

FLUID-6691: docs for UIO's css custom props

---

src/documents/DeprecatedIn3_0.md

See [FLUID-6719](https://issues.fluidproject.org/browse/FLUID-6719) for details.

FLUID-6719: Added migration notes about minified bundles.

---

package.json

GH-209: Ensure that everything is built before test runs (resolves #209).

---

src/documents/EventInjectionAndBoiling.md

GH-237: Fixed event injection and boiling example (resolves #237).

---

src/documents/EventInjectionAndBoiling.md

GH-240: Update and reorganise docs on event injection to make preferred approached clearer

---

License-code.txt
License.txt
src/_includes/layouts/base.njk

Resolves #221 
- Add license info to footer
- Adds BSD-3 Licence file to project
- Updates documentation license to CC BY 4

feat: add license info to footer (resolves #221)

---

.github/workflows/ci.yml
src/static/css/infusion-docs.css

Resolves #242 
- Updates css to apply to all heading levels
- fixes focus styling to show link icon when focused
- bumps CI action versions to latest

fix: hover icon does not appear on anchors for headers of level h4 (resolves #242)
